# Generated by Django 3.2.2 on 2021-05-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeEntSys', '0002_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
