# Generated by Django 3.2.2 on 2021-05-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=50)),
                ('proj_is_active', models.BooleanField(default=True)),
                ('proj_created_at', models.DateTimeField(auto_now_add=True)),
                ('proj_updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['proj_name'],
            },
        ),
    ]
