# Generated by Django 3.2.2 on 2021-05-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['proj_name'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
